services:
  instagram-reels-bot:
    build: .
    container_name: instagram-reels-bot
    restart: unless-stopped
    ports:
      - "3666:3666"
    environment:
      - NODE_ENV=production
      - PORT=3666
      - BOT_TOKEN=${BOT_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./reels_cache.db:/app/reels_cache.db
    command: ["npm", "run", "bot"]

